### ISSUE TITLE
roadmap: Docs Rewrite

### ISSUE THREAD

**Issue by ilxlodev** [filobot/docs-rewrite#1]
**Tasks**
- Repository Documentation:
  - [x] Document how to make changes using PR and Forks.
  - [ ] Contribution Guidelines.
  - [ ] Code of Conduct.
  - [ ] Templates for issues.
  - [ ] Pull Requests Templates.
  - [ ] SUPPORT.md File.
  - [x] README.md File.
  - [ ] LICENSE.md File.
- Getting Started section:
  - [x] Invite.
  - [x] Modules.
- Administration modules section:
  - [x] Commands.
  - [x] Disable Commands.
  - [ ] Guild.
  - [ ] Guild: Muted Role.
  - [ ] Guild: Role.
  - [ ] Guild: Preset Packages.
  - [ ] Member-Counter.
  - [ ] Member-Counter: Nickname.
  - [ ] Reports.
- Community modules section:
  - [x] Farewells: Variables.
  - [x] Language.
  - [ ] Logging.
  - [ ] Welcomes.
  - [ ] Welcomes: Role.
  - [x] Welcomes: Variables.
- Moderation section:
  - [ ] Anti-Bad-Words.
  - [ ] Anti-Evasion.
  - [ ] Anti-External-Links.
  - [ ] Anti-Invites.
  - [ ] Anti-Mass-Mentions.
  - [ ] Anti-Repeteated-Text.
  - [ ] Anti-Scam-Links.
  - [ ] Anti-Spam.
  - [ ] Auto-Moderation.
  - [ ] Moderation-Parameters.
  - [ ] Moderation-Parameters: DM-Notifications.
- Topics section:
  - [x] Cloudflare.
  - [x] ~~Common Errors.~~
- Other tasks:
  - [ ] Repository labels.
  - [ ] Repository workflows.
  - [ ] Review the repository configuration.
  - [ ] Rename the repository (when the documentation is completely finished).
  - [ ] Wiki maintenance.

**Additional details**
- Variables used so far: `LINKS_MAIN`, `LINKS_BLOG`, `LINKS_GITHUB_DOCS_REPO`, `GITHUB_DOCS_REPO`.
- This repository will contain several branches, one of the branches, which are:
  - `main`: Default branch of the repository. Includes essential repository files. Used for raw documentation, it does not contain the documentation header and contains unparsed links.
  - `stable`: Used for the final documentation that takes the Wiki as a reference. Contains translations and parsed links.
  - `canary`: Similar to the stable branch, but with more abrupt and sustainable changes.

**Comment by ilxlodev** [comment]
Taking up this roadmap again! The different tasks are worked on as the commands of the Settings category are refactored.
